server:
  port: 8902
webSocket:
  netty:
    port: 9901
# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Bearer_
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico
spring:
  application:
    name: MessageServer
  datasource:
    druid:
      url: jdbc:mysql://54.169.161.137:3391/customer?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: webuser
      password: nq3J4wh2VsqwV7Wz3T2R^VGn6AJ39dWr
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #initialSize: 10
      minIdle: 50
      maxActive: 100
      maxWait: 60000
      time-between-eviction-runs-millis: 60000
  redis:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 50
        #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
        shutdown-timeout: 100
        #是否缓存空值
        cache-null-values: false
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 50000
    #单机配置
    host: paydev.mvkbnb.com
    password: pukswxpnq5NQ5CTZK8A6aCHaxyJdVtET
    port: 21121
    database: 0
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl